### ISSUE TITLE
DBに処理させた方が速いと思える

### ISSUE THREAD

**Issue by nenaaki** [Stein-3/chat#21]
https://github.com/Stein-3/chat/blob/ca6e994f3b60419e87992c3c82ba1067f99cf69f/Server/Services/PostService.cs#L43-L44

OrderByやTakeLastはSQLで処理したほうが良さそうです。つまり、EFCoreのLinqに含めることを提案します。

**Comment by Stein-3** [comment]
TakeLastはEFCoreに対応していないようです。使おうとすると以下のエラーがでました。
そのため、OrderByをEFCoreのLINQに含めて、TakeLastだけ別に実装しました。

> could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
